const btn = document.getElementById('submit-btn')
const name = document.getElementById('naem-input')
const email = document.getElementById('email-input')
const password = document.getElementById('password-input')
const textarea = document.getElementById('textarea-input')
